name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  firebase_database: ^3.1.6
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.10
  http: ^0.12.0+2
  intl: any
  url_launcher: ^5.4.1
  charts_flutter: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: Lobster
      fonts:
        - asset: font/Lobster-Regular.ttf
    - family: Roboto
      fonts:
        - asset: font/roboto.thin.ttf
    - family: RobotoLight
      fonts:
        - asset: font/roboto.light.ttf
    - family: RobotoBold
      fonts:
        - asset: font/roboto.bold.ttf
